openapi: 3.1.0
info:
  title: All Things Puzzles
  description: OpenAPI Specification for the All Things Puzzles API
  version: 1.0.0
paths:
  /users:
    get:
      description: Get all Users
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  /user:
    get:
      description: Get User by their User ID
      parameters:
        - name: id
          in: query
          description: The User ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: User not found!
  /brands:
    get:
      description: Get all Brands
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Brand'
  /brand:
    get:
      description: Get User by their User ID
      parameters:
        - name: id
          in: query
          description: The User ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: User not found!
components:
  schemas:
    Brand:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 28
        name:
          type: string
          example: MasterPieces
      required:
        - id
        - name
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        username:
          type: string
          example: example
        fullname:
          type: string
          example: Example Exampleton
        email:
          type: string
          example: example@example.org
        emailconfirmed:
          type: boolean
          example: false
        groupid:
          type: integer
          example: 2
        themeid:
          type: integer
          example: 1
        lastlogin:
          type: string
          example: "2025-01-01 12:00:00"
      required:
        - id
        - username